### ISSUE TITLE
Cannot modify access list

### ISSUE THREAD

**Issue by jmtemmos** [noshutdown-ru/vault#14]
When trying to access access list for a key, from available members, no error raised but nothing is saved and access list is always empty.

Redmine logs  give the following hint :

WARNING: Can't mass-assign protected attributes for Vault::Password: tags
        plugins/vault/app/controllers/keys_controller.rb:101:in `block in update'
        plugins/vault/app/controllers/keys_controller.rb:97:in `update'
        lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Redmine 3.4.2
Ruby 2.4.2
Rails 4.2.8
Vault Redmine plugin  0.3.3

**Comment by noshutdown-ru-user** [comment]
we take a look, but we don't test it yet on Redmine 4.4.2

**Comment by jmtemmos** [comment]
Hello. Sorry or was a typo. It is redmine 3.4.2. Thanks a lot

Le 24 oct. 2017 06:30, "noshutdown-ru-user" <notifications@github.com> a
écrit :

**Comment by noshutdown-ru-user** [comment]
we working on it, soon it should be fixed, couple of days

**Comment by noshutdown-ru-user** [comment]
sorry for this lateness, we will take it process during a this week

**Comment by jmtemmos** [comment]
Hello. I'm afraid bug is back:
Redmine version                3.4.2
Ruby version                   2.4.2
Rails version                  4.2.8
Vault Redmine plugin 0.3.7

**Comment by noshutdown-ru-user** [comment]
ok we take a look, can add screenshots end logs

**Comment by if22** [comment]
Got the same on
>   Environment:
>   Redmine version                3.3.5.stable
>   Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
>   Rails version                  4.2.7.1
>   Environment                    production
>  vault                          0.3.7

Production log:
``` 
WARNING: Can't mass-assign protected attributes for Vault::Password: tags plugins/vault app/controllers/keys_controller.rb:80:in 'create'
lib/redmine/sudo_mode.rb:63:in 'sudo_mode'
Completed 500 Internal Server Error in 28ms (ActiveRecord: 4.9ms)

ArgumentError (must specify a :key):
plugins/vault/app/models/vault/password.rb:8:in `encrypt!'
plugins/vault/app/controllers/keys_controller.rb:88:in `block in create'
plugins/vault/app/controllers/keys_controller.rb:87:in `create'
lib/redmine/sudo_mode.rb:63:in 'sudo_mode'
```

**Comment by noshutdown-ru-user** [comment]
Do you have other Password store plugins ? or maybe you use incorrect encryption key. As i can see it happened when you created key.
https://github.com/noshutdown-ru/vault/issues/30

**Comment by if22** [comment]
We have redmine_wiki_encryptor plugin installed. 
Ok, I'll check this soon.

**Comment by if22** [comment]
Remove redmine_wiki_encryptor fixed my issue. Thanks!
